---
language: go

go:
  - '1.12.x'
  - '1.13.x'
  - '1.14.x'

env:
  - GO111MODULE=on
    CMAKE_VERSION=3.16.4
    GOLANGCI_LINT_VERSION=v1.23.7

compiler:
  - gcc

install:
  # first we create a directory for the CMake binaries
  - DEPS_DIR="${TRAVIS_BUILD_DIR}/deps"
  - mkdir ${DEPS_DIR} && cd ${DEPS_DIR}
  # we use wget to fetch the cmake binaries
  - travis_retry wget --no-check-certificate https://cmake.org/files/v3.16/cmake-${CMAKE_VERSION}-Linux-x86_64.tar.gz
  - echo "12a577aa04b6639766ae908f33cf70baefc11ac4499b8b1c8812d99f05fb6a02" cmake-${CMAKE_VERSION}-Linux-x86_64.tar.gz" > sha256sum.txt
  - sha256sum -c sha256sum.txt
  - tar -xvf cmake-${CMAKE_VERSION}-Linux-x86_64.tar.gz > /dev/null
  - mv cmake-${CMAKE_VERSION}-Linux-x86_64 cmake-install
  - PATH=${DEPS_DIR}/cmake-install:${DEPS_DIR}/cmake-install/bin:$PATH
  - cd ${TRAVIS_BUILD_DIR}

script:
  - make test
  - make test-skipped

jobs:
  include:
    - stage: lint
      go: 1.13.x
      script:
        - curl -sfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh
          | sh -s -- -b $(go env GOPATH)/bin $GOLANGCI_LINT_VERSION
        - golangci-lint run ./...
